# C?ng ch?y c?a API Gateway
server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          # === TV1 (Search) ===
          - id: search_service
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/search/**

          # === TV2 (User & Auth) ===
          - id: auth_service
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/auth/**
          - id: profile_service
            uri: http://localhost:8083
            predicates:
              - Path=/api/v1/profile/**
          - id: email_service
            uri: http://localhost:8084
            predicates:
              - Path=/api/v1/notification/**

          # === TV3 (Catalog & Content) ===
          - id: movie_service
            uri: http://localhost:8085
            predicates:
              - Path=/api/v1/movies/**
          - id: theater_service
            uri: http://localhost:8086
            predicates:
              - Path=/api/v1/theaters/**
          - id: review_service
            uri: http://localhost:8087
            predicates:
              - Path=/api/v1/reviews/**

          # === TV4 (Core Logic) ===
          - id: room_service
            uri: http://localhost:8088
            predicates:
              - Path=/api/v1/rooms/**
          - id: showtime_service
            uri: http://localhost:8089
            predicates:
              - Path=/api/v1/showtime/**

          # === TV5 (Transaction) ===
          - id: booking_service
            uri: http://localhost:8091
            predicates:
              - Path=/api/v1/booking/**
          - id: payment_service
            uri: http://localhost:8092
            predicates:
              - Path=/api/v1/payment/**
          - id: ticket_service
            uri: http://localhost:8093
            predicates:
              - Path=/api/v1/ticket/**
          - id: checkin_service
            uri: http://localhost:8094
            predicates:
              - Path=/api/v1/checkin/**
          - id: push_service
            uri: http://localhost:8095
            predicates:
              - Path=/api/v1/push/**